### ISSUE TITLE
N3C CTSA Webinar back on for Friday 15th

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#10]
We need to schedule the **N3C CTSA Webinar** for Friday the 15th either at 10am, 11am or 12 PT. 

- [ ] Need to contact the list of potential attendees after Melissa has reviewed the list with NCATS

- [ ] Need to schedule a time for the Friday Webinar by tomorrow

- [ ] Need to Send out to CTSA an announcement by Tuesday COB (draft language)

- [ ] Update the News Bulletin with dates and times by Wed 12pm or sooner

- [ ] Draft slides for the session by Thursday

- [ ] Place announcement on Website, send to CLIC, TIN....Ask members to send to institutions

**Comment by dietzr** [comment]
Friday's webinar has been scheduled. Attendees were contacted for their availability via email and at the leadership standup.
