### ISSUE TITLE
Edits needed re: Enclave registration form

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#101]

**Comment by cgcook** [comment]
Hi @eichmann pls see [here](https://docs.google.com/presentation/d/14ZFzZJClSm_F-JLIsuE6vDPuBn6qxMVBvKwy76OR2bM/edit#slide=id.g916d37c41e_0_0) for edits/clarifications needed on the current N3C registration form.  Thx.

**Comment by cgcook** [comment]
@alexisgraves are you able to make [the edits](https://docs.google.com/presentation/d/14ZFzZJClSm_F-JLIsuE6vDPuBn6qxMVBvKwy76OR2bM/edit#slide=id.g916d37c41e_0_0) to the form?  

Let me know if you have questions.

**Comment by alexisgraves** [comment]
@cgcook Yep! :) I've edited the pages accordingly and sent the changes off to @eichmann . I think he is finalizing some of the other components based on additional feedback and planning to go live with the changes soon. There might be some additional review/approval processes that I'm not involved with so I've tagged him just in case.

**Comment by cgcook** [comment]
Awesome, thanks @alexisgraves.

**Comment by cgcook** [comment]
@eichmann do you have an ETA on the updated registration form going live?  The current language is no longer accurate.

**Comment by cgcook** [comment]
updated form live.
