### ISSUE TITLE
DUR training message. 

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#102]
The statement on the DUR says that 1 or more training is required but it seems that both trainings are required even for a Citizen Scientist.

**Comment by amvolz** [comment]
✔ Completion of Standard NIH IT Security Training (Each individual data user must complete the first listed course that contains 4 modules; allow 60-90 minutes.)
✔ Completion date of Human Subjects Research Protection training (within the last 3 years), if you intend to access the de-identified or limited datasets. (Not needed to access the synthetic dataset.) CITI Program and NIH courses are most common; consult your institution for your required Human Subjects Research Protection course.)

**Comment by cgcook** [comment]
status check: is this still an open ticket?  

@deacyma @amvolz

**Comment by amvolz** [comment]
This is done.
