### ISSUE TITLE
DUR - add "IRB"

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#103]
People do not know what HRPP is?  Can we add "IRB Determination Letter" be added if it is the same thing?

**Comment by amvolz** [comment]
An IRB is set up as part of a Human Research Protection Program (HRPP) to protect human subjects, per regulation. So it is technically the Human Research Protection Program (HRPP)'s IRB Determination Letter. (But that's a mouthful.)

**Comment by cgcook** [comment]
@deacyma -- can you confirm clarifying language has been added to the DUR re: HRPPR / IRB?
