### ISSUE TITLE
NIH not in DUR list of organizations

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#104]
NIH and Arizona not in DUR list of organizations

**Comment by deacyma** [comment]
@waldenan could you please clarify in what organization list the NIH the user did not see the NIH?

**Comment by waldenan** [comment]
Mariam, I think there is only one field on the DUR that ask for Organization name. The one they were completing was labled: "Accessing Institution"

**Comment by deacyma** [comment]
@waldenan the "Accessing Institution" field should get auto populated from the users login information.

**Comment by waldenan** [comment]
I agree. When users were in the field they could see a list of organizations but NIH wasn't on that list.

**Comment by cgcook** [comment]
status check: is this still an open issue?  @deacyma
