### ISSUE TITLE
Need a next steps message when registration is completed

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#106]
When people complete their N3C Registration form they want something on the screen to indicate next steps. We need a written message that states... Thank you for registration, you will receive an email with instructions within the next 24-72hrs for creating your N3C Data Enclave Account. 
they are receiving an email but many don't realize it. Closure is needed on the actual screen once they submit. Use N3C logo if possible for branding.

**Comment by amvolz** [comment]
Screen message has been created: https://docs.google.com/document/d/1jk8TEzws1PIGWB_fzZvPyYBCqsykxxMe1XFuU5Zqa3o/edit

**Comment by cgcook** [comment]
@eichmann is this screen message now implemented?  Pls comment/close if so.

**Comment by eichmann** [comment]
Done.
