### ISSUE TITLE
Check the Organization name text for UTMB

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#107]
Heidi Spratt said that the text for her Organization name looks odd in the Registration form and DUR form. Can someone double check the text.

**Comment by eichmann** [comment]
How is "University of Texas Medical Branch At Galveston" odd?  Granted, the DTA/DUA spreadsheet entry is funky...

**Comment by waldenan** [comment]
University of Texas Medical Branch at Galveston, d/b/a UTMB Health (UTMB). Heidi wasn't sure what d/b/a meant in her institution's name.  I am bringing it to your attention because she questioned it.

**Comment by eichmann** [comment]
Verified that Heidi was looking at NCATS spreadsheet, not registration site.

**Comment by cgcook** [comment]
status check: is this still an open/pending issue?

**Comment by eichmann** [comment]
Nope.
