### ISSUE TITLE
Not expecting to see Gmail account

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#108]
A couple of people have mentioned that the CD2H gmail looks suspicious to some users. They said it doesn't look official and do not expect a CTSA or NIH organization to have a gmail account registered on documents or in emails.    This has been a issue identified at other organizations which caused emails to be deleted and important messages overlooked.

**Comment by eichmann** [comment]
If we don't use gmail, my only other option is our institutional mail servers, which enforce the sender being me.  I tried specifying an override and my institutional server rejected the message. As it is, gmail overrides the sender email with the actual account address, but leaves the sender name as specified. I asked NCATS about options, but they don't support outboard email services.

Our domain name services are from GoDaddy.  We can configure email service with them, but it would cost $6/mo/account.

**Comment by cgcook** [comment]
Status check: is this still an open issue?

**Comment by cgcook** [comment]
@waldenan per @eichmann's comment above, there is a cost associated with using a non-Gmail address.  Should we explore that option, or keep using data2health@gmail.com? 

We have a CD2H@ohsu.edu account that the OHSU admin core can send from; would this be an acceptable alternative?

**Comment by eichmann** [comment]
I've come up with an alternative solution (no cost) that I just need to work on. The application containers on the server need to be able to send these messages.  We don't want to necessitate human intervention.

**Comment by eichmann** [comment]
Sorry - didn't mean to close - hit wrong button!
