### ISSUE TITLE
Add N3C to covid website url link

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#109]
A couple of people asked if N3C should be in the url link. Can this be done without a lot problems.  N3C.CD2H,edu?

**Comment by eichmann** [comment]
Trying to change domain names at this point could incur serious link breakage at a critical stage for the project. We need to hold on this until more consideration can be given to the implications.

**Comment by waldenan** [comment]
OK We will keep this as a parking lot issue to revisit. Thank you.

**Comment by andrewjneumann** [comment]
Is [jira issue 228](https://n3c-help.atlassian.net/browse/N3CSUPPORT-228)
