### ISSUE TITLE
Clinical Scenarios and Data Analytics Google Group  (listserv) needed this week

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#11]
As indicated last week we need a Google Group (listserv) for the Collaborative Analytics Workstream Subgroup- **Clinical Scenario and Data Analytics** 

We need it this week (by Thursday) so a meeting reminder can be sent on **Friday.** 
This list should be populated with those who have been invited and who have attended the Clinical Scenario and Data Analytics group. It should be compared with emails that were sent asking for members to be added to the invite.  

I don't know how to assign the primary owner but this should be Andrew with help from others (Rafael and Connor).

- [ ] Responsible for task Completion 

- [x] Create a Google List 

- [x] Populate the names

- [ ] Use it on Friday to send out Meeting Reminder for the Clinical Scenario and Data Analytics Subgroup- **Rafael**

**Comment by andrewjneumann** [comment]
https://groups.google.com/forum/#!forum/n3c-clinical has been created. Per standup yesterday, names need to be added to the group, set email w/ questions last night.

**Comment by andrewjneumann** [comment]
Invited people that were on @racquel's list. We should send this Friday's email to both lists, groups will only deliver one.
