### ISSUE TITLE
Example DUR

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#110]
A user said it would be helpful to see a DUR completed especially the information needed by the DAC for a description of a project. They are not sure exactly what they want to see. What types of tools.

**Comment by cgcook** [comment]
@waldenan -- can you clarify this request?  Where would you like the example DUR linked?  

@deacyma -- is it possible to create an example DUR?

**Comment by cgcook** [comment]
We have the sample DUR form on [this](https://covid.cd2h.org/Enclave_Registration_Checklist) page.  In absence of further details on the request, closing this ticket.
