### ISSUE TITLE
List of N3C Enclave Tools and Resources on Webpage

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#113]
User asked for list of tools to complete the Research Rationale.

Work with Andrew Willians and Chunlei to come up with a list of tools that can be displayed on the Research Resources webpages.  Use the CD2H Tool database format?

**Comment by cgcook** [comment]
@jaeddy @eichmann please provide an update on this issue.

**Comment by cgcook** [comment]
@eichmann any update on this ticket?

**Comment by amvolz** [comment]
This should be moved to the covid website repository. 
[Tools page ](https://covid.cd2h.org/node/385) has been drafted and is in the works. 

OMOP tools: Atlas is not yet in Foundry but discussions about porting it into Foundry (will be awhile)
R vs Python: why, difference, what can you do, training 
Dave will get logs to concentrate curation effort on high value tools.
Give Andrew Williams a heads up for Integration meeting.
This is on Dave's list of widgets to build
