### ISSUE TITLE
DUR- Project Rationale: Add to the instructions Project has to be COVID Research

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#118]
Project Rationale: Add to the instructions Project "Indicate how the research project question is COVID Research related" ...or something similar to this text.

Per Melissa and Anita during the PM mtg. 24Aug

**Comment by amvolz** [comment]
@waldenan Please provide clarification on what exactly you would like done. It is not clear what the "Instructions Project" refers to or where it is located.

**Comment by amvolz** [comment]
@waldenan After reading a few more times, I see you mean to add the statement: "Project has to be COVID research" to a list of instructions. Please let me know what instruction list this refers to and where it resides. Thank you!

**Comment by amvolz** [comment]
@waldenan After more investigation, I think you might mean [this document](https://docs.google.com/document/d/1xKS6BURQHGfnstgVJSuYZzDBws4PuIyyz1QDnc-8hjI/edit)?

**Comment by waldenan** [comment]
The instructions for the Project Rationale from the DUR. 

- Sufficient information for the Data Access Committee (DAC) to understand the proposed research project and analyses
- Rationale for the requested level of access needed to conduct the proposed work
- A generalized outline of anticipated analysis
- Software expected to be used in the N3C Data Enclave during the course of the research project. (As stated in the DUA, all software must be approved in writing by N3C prior to being uploaded.)

**Comment by cgcook** [comment]
@deacyma - has the updated language been added to the DUR form? Please provide an update on this issue and/or close if resolved.

**Comment by deacyma** [comment]
The instructions have been updated
