### ISSUE TITLE
DUR- Project Rationale: Remove Tools from the Instructions list of requirements by the DAC

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#119]
- [x]  Project Rationale: Remove the text about the "Tools" from the Instructions list of requirements by the DAC.

- [x] Update Account Creation Checklist on website and FAQs- Andrea

Per Ken 24August - Project Stand up

**Comment by amvolz** [comment]
@waldenan Can you clarify your instructions? There is no mention of tools on the checklist. Are you trying to say that you want the sentence about software deleted?

**Comment by waldenan** [comment]
This is the sentence that should be removed....  Software expected to be used in the N3C Data Enclave during the course of the research project. (As stated in the DUA, all software must be approved in writing by N3C prior to being uploaded.) @KenGersing will you confirm.

**Comment by amvolz** [comment]
Thank you for clarifying. It has been deleted from the website checklist, and the checklist on the FAQ Google doc that is still under NCATS review.

**Comment by cgcook** [comment]
@amvolz per your last comment, is this issue resolved?  Please close if so.
