### ISSUE TITLE
DUAs Executed!

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#120]
For the organizations that have a DUA signed we do not want to show the contact names on the website at this time.  Will you remove the names. 

Those who **d**on't**** have a DUA they want to know the contacts so they can follow up on the status.

https://covid.cd2h.org/enclave_DUA_signatories

**Comment by cgcook** [comment]
per N3C admin call: [collapse 2 contacts columns to one contact](https://covid.cd2h.org/enclave_DUA_signatories).

**Comment by eichmann** [comment]
Page now displays institution, contact name and execution date, as per yesterday's discussion.
