### ISSUE TITLE
N3C FACT SHEET will be on the Research Resource Area of the Website

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#124]
All we need to place the N3C Fact Sheet on the N3C website. For now it is a document but in the future we hope it will come from the Enclave.

https://docs.google.com/document/d/1-hOK6dslNGHHNeJN1GCTiZU9xZI3KCc5QCelJdpak-A/edit

also include in Zenodo.

**Comment by cgcook** [comment]
@alexisgraves @amvolz - can you confirm if the linked Fact Sheet is on the web?  I'm not finding it.

@waldenan - pls confirm the linked Fact Sheet should still be uploaded to Zenodo, and I will do so.

**Comment by amvolz** [comment]
@cgcook It is not currently on the website. It would need to be published in Zenodo first before it can be linked to a place on the website.
