### ISSUE TITLE
Data Enclave Checklist - link to list of DUAs signed

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#126]
[N3C Registration Checklist ](https://covid.cd2h.org/Enclave_Registration_Checklist)

First line:
Confirmation that an executed DUA exists between your organization exists between your organization and NCATS. 
Change the link from the PDF DUA to the list of DUAs.

https://covid.cd2h.org/enclave_DUA_signatories

**Comment by alexisgraves** [comment]
The link has been updated to point to the DUA Signatory List :)

**Comment by amvolz** [comment]
@alexisgraves Not sure what happened. The Checklist was still pointing to the PDF just now, so. I just changed it to the DUA Signatory List.

**Comment by alexisgraves** [comment]
Sorry, the link was changed but the text was not.

**Comment by amvolz** [comment]
can close

**Comment by eichmann** [comment]
Verified working and link to live list.
