### ISSUE TITLE
Add DUO - Mobile Authenticator Setup for Palantir 

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#127]
Mobile Authenticator Setup for Palantir - Palantir  Unite Authenticator.
1. Install one of the following Applications on your Mobile 
DUO is not listed but is popular in Academic Centers will you add it.

Also will you remove "Palantir" and replace it with "N3C Data Enclave".

We want "N3C Data Enclave" or "N3C Enclave" as the official name instead of Palantir on outward facing communication.  

I don't see that Keats has a Github handle so I am passing it to @deacyma

**Comment by keatsk** [comment]
Hi Anita.  I'm not sure what document you are referring to.  The one I created which is linked to the login page is here:

https://docs.google.com/document/d/1_QQSpABRHgRP5lJMKsE_2eCHdHny84mcspucotY0mus

It does include Duo in the list of authenticator apps and does not mention Palantir (or the N3C Enclave).

**Comment by waldenan** [comment]
Hi! The screen shot that you have on the documentation shows what I am referring to. The authentication page doesn't have Duo listed. When people land on that screen it shows only 3 options. Also Palantir appears on this screen.
<img width="552" alt="Screen Shot 2020-09-04 at 4 37 36 PM" src="https://user-images.githubusercontent.com/62001577/92291351-1bc7b280-eecd-11ea-84bd-5845efd67c88.png">

**Comment by keatsk** [comment]
Gotcha. So this is a request to change the mobile authenticator registration page.  We can definitely add Duo to the list.

I was able to change the heading by updating the display name for the application in UNA.  See below:

![image](https://user-images.githubusercontent.com/17165689/92310365-951dde80-ef7b-11ea-8e02-d4d0ada1cc04.png)

**Comment by cgcook** [comment]
@keatsk - it appears this issue has been resolved.  Pls re-open if not.
