### ISSUE TITLE
What is the DAC email address. I am getting reports that the email for DAC is bouncing back. This is the email address sent to me:  NCATS.N3CDAC@nih.gov

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#129]
I am getting reports that the email for DAC is bouncing back. This is the email address sent to me:  NCATS.N3CDAC@nih.gov

I am assuming this is in the DUR process where the email address need to be updated.

**Comment by deacyma** [comment]
Hi @waldenan 

I just sent an email to the email address: NCATSN3CDAC@mail.nih.gov and confirmed that the email was received without bouncing back
![image](https://user-images.githubusercontent.com/22172108/94056719-a9037600-fdac-11ea-87e3-f486fbb6056e.png)

I noticed that there is "." after the NCATS in the email you provided.
