### ISSUE TITLE
Offboarding form needed

### ISSUE THREAD

**Issue by jmcmurry** [National-COVID-Cohort-Collaborative/operations#130]
We need a form analogous to the registration form wherein someone can signal they'd like to be:
- Removed from enclave access
- Removed from google groups

The former needs a tight workflow confirming their removal
The latter would generate a self-serve email with links to unsubscribe from all the groups of which we know they're a member.

I don't think we need to be overly concerned with forcibly removing access to docs, at least not unless someone proves themselves a vandal.

**Comment by andrewjneumann** [comment]
Is [Jira issue 229](https://n3c-help.atlassian.net/servicedesk/customer/portal/2/N3CSUPPORT-229)
