### ISSUE TITLE
Harmonize names on the registration form.

### ISSUE THREAD

**Issue by jmcmurry** [National-COVID-Cohort-Collaborative/operations#133]
- Require user to supply a name if one is not provided by the registration mechanism; several are missing
- Normalize the stored name
    - Trim whitespace (See Lana for an example)
    - Prompt user to check the casing if it is all lowercase or all uppercase (nice to have)

**Comment by cgcook** [comment]
@jmcmurry @eichmann is this still an open ticket?  We are migrating open issues to Jira.  Pls advise.  thanks!

**Comment by andrewjneumann** [comment]
is [Jira issue 230](https://n3c-help.atlassian.net/servicedesk/customer/portal/2/N3CSUPPORT-230)
