### ISSUE TITLE
new email for DUR project space set up and onboarding

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/operations#136]
The current email is here: 

Hi all,
This is Kate, a member of the Palantir team involved in assisting researchers with their analyses. I’d like to offer my congratulations for obtaining access to data within the N3C Data Enclave and help you move forward with your project, a link to your new project workspace is below. I’d be interested to hear your plans for the project, which analysis resources you’d need, and any planned involvement and interests in N3C domain teams (https://covid.cd2h.org/Domain_Teams [covid.cd2h.org]).
Project name: [RP-7D14B0] [N3C Operational] Collaborative Analytics
Project workspace: https://unite.nih.gov/workspace/compass/xxxxxxxx [unite.nih.gov]
Datasets can be found under the References tab within your workspace.

We need to include:
info about the domain teams and clinical scenarios
info about office hours
onboarding weekly sessions
help desk/ticketing system info

The email should be signed from the N3C leadership

**Comment by andrewjneumann** [comment]
this was passed to ken last week, followed up via email yesterday.
