### ISSUE TITLE
Action Item Tracking System

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#15]
All, I am not sure if there is a ticket for this but here are some requirements for the action item list.

- One Click overview of all action items by date with an alert when items are pass due
- Overview one page of all action items by Workstream and sub groups (new, closed, pending) with notes by date that may explain what is taking place (ex. why pass due)

- Date action was opened, date last modified, date closed, projected to be completed date, actual completed date, dated notes, owner of action item.
A way to track date changes (see previous deliverable dates)

- Sort Actions by open overall project and by workstream; ability sort by name

-Simple priority levels Ex. (1-3) 1=high priority (complete w/in 24hrs); 2=medium (by next meeting) 3=Low) *we shouldn't have more than 25% of Level 1s

- Workstreams need to have one-click view.  People like John Wilbanks and Tell Bennett need to be able to Click on the link and immediately see the list of all open action items for their group with names of owners and projected completion dates.

User-centered design principles should be exercised. Should be very simple for someone like Tell, Justin or Ken (or anyone with a heavy workload and doesn't have time to try to figure it out) to enter an action item with the projected date and assign someone <7min or without training.

**Comment by cgcook** [comment]
current action item tracking:

Workstreams: in notes doc
Ops: in GitHub
Enclave Support Desk: in GitHub

closing ticket; pls re-open if needed.
