### ISSUE TITLE
Dashboard for Hub tracking

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#16]
A Site dashboard to track the various stages of the sites readiness is needed. [Hub Tracking and Requirements](https://docs.google.com/spreadsheets/d/1btafAid_yWUbO6gsZzWOSVRtuipuiQRzmsMxLMJzyhw/edit#gid=0)

[DTA Tacking](https://docs.google.com/spreadsheets/d/1erpo_8QChByp-yqk0tfYutKPzjmeoWRvrkDO1QQ_YfE/edit#gid=0)

**Comment by waldenan** [comment]
@eichmann 

I have gone through the Hub Dashboard Worksheet spreadsheet and standardized the data but it hasn't been validated by a 2nd person yet.
Ignore the following columns: "D" and  "E" For columns E and AB I haven't changed it in the spreadsheet yet but it should be Yes only response. I am not used to working with Google sheets so I have to figure out how to change it.To separate multiples in a field, I used a semi colon to help those who are using the spreadsheet.I made the following Column Change : Added Other Contact Email  which is now column "K"
If there is only one name in the column assume it is a last name.

Let me know if you see anything else I should fix.

**Comment by waldenan** [comment]
We need an aggregate spreadsheet/view of the following information by site. Similar to the spreadsheet we have.

**Data sources:**

Data Source 1 
[Data Sources](https://docs.google.com/spreadsheets/d/1erpo_8QChByp-yqk0tfYutKPzjmeoWRvrkDO1QQ_YfE/edit#gid=0)
DTA/DUA tracking spreadsheet

Columns to include in Dashboard: 
Column A -Match Site names with other spreadsheets
Column C - DTA Sent
Column D -DTA Executed
Column E - DUA Sent
Column F -DUA Executed

Data Source 2
[Hub Status Dashboard](https://docs.google.com/spreadsheets/d/1btafAid_yWUbO6gsZzWOSVRtuipuiQRzmsMxLMJzyhw/edit#gid=0)

Columns to Include:
Column A - Match Site names with other spreadsheets
Column C - CTSA/Community
Column E- Groups/Consortium
Column F - Person to Make Contact
Column G - Contact Made
Column H - PI Contact at Site
Column I -PI Email
Column Z- Status of Data Ingest
Column AA - Status of Data Ingest Date
Column AC -Date Script Sent to Site
Column AD -Date Initial Data Received
Column AE -Data Update Frequency
Column AF - Notes


Data Source 3 Title: **N3C sIRB and local IRB Tracking Detail** [IRB Tricia](https://docs.google.com/spreadsheets/d/1kh8UVT239XHHiHPCMTUhiVJWz3Mfx-S4gRrcHGNEVJs/edit#gid=1672062498
)
Submitted to eIRB for Review
sIRB Approved
 local IRB Approved
Receipt of local IRB Approval Letter
Need Derived Data Element - Approval process completed (DTA Executed AND sIRB Approved or Received of Local IRB Approval letter)

Data Source  4
**Title: Data Acquisition Site Tracker**
Location: [Data Acquisition Site Tracker](https://docs.google.com/spreadsheets/d/1_uZUFcutAG1HWFBPjgosNcVFtm-1_bBm3owqJrzJAzU/edit#gid=0)
Owner: Phenotype & Data Acquisition group
Columns we think others may want us to share:
Column B - Data of first meeting
Column D - Primary technical contact(s)
Column E - Data model used
Column G -  Passing Data 

Data source 5 
[Synthetic Clinical Data Tracking Dashboard](https://docs.google.com/spreadsheets/d/1MS7sVv_3apGChBQ8LajFWKUTxneZECElptpEeAnQb2A/edit#gid=0)

For the website. This is what can be published for public view on the website..

DTAs Sent
DTAs Executed 
IRB  Approvals
Both DTA and IRB Complete
Sites that Submitted Data

All other information should only be seen by Leadership and Admin group.

**Comment by mellybelly** [comment]
@jmcmurry @andrewjneumann are working on the source spreadsheet I believe

**Comment by waldenan** [comment]
@eichmann is it possible to provide @jmcmurry and shawn O'Neil the mappings of institution names across the spreadsheets?

**Comment by waldenan** [comment]
> @jmcmurry @andrewjneumann are working on the source spreadsheet I believe...

Andrew so far hasn't been brought into this discussion. It has been shawn

**Comment by waldenan** [comment]
@jmcmurry For those Users Organizations who do not have FWAs what will be used? Some will have a IRB or/and DUA but not DTA. For example Sage may not have a FWA.
