### ISSUE TITLE
Governance Meeting - AI: Talk with Ken about DAC and Steering committee -

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#17]
ACTION ITEM: Melissa will talk to Ken about sending the DAC to CTSA Steering Committee and NCATS, N3C Steering committee (doesn’t include Synthetic data) - update on AI requested by May 19th

**Comment by mellybelly** [comment]
I am happy to send once i know the documentation is ready. Can @cfsuver confirm what to send?

**Comment by waldenan** [comment]
To clarify, I think you were planning to talk to Ken if we should send the DAC to the CTSA Steering Committee, CD2H Steering Committee and NCATS to review once it is ready.  A process questions... Thanks!
