### ISSUE TITLE
Adding Chats to the meeting notes

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#18]
There was a request to add the Workstream meeting Chats to the notes. Can we look into seeing if that is possible and if so, can we plan to implement it by next Wed or Thursday?

- We will need the method
- Document the process in a document
- Identify who is responsible for adding the the chat
- Communicate it during the Admin Stand up

**Comment by cgcook** [comment]
Method: to capture the chat dialogue, the webinars or meeting must be recorded. At the the end of the meeting, Zoom produces a .txt file of the chat dialogue and sends to the host.

Process [here](https://docs.google.com/document/d/1uXW0gPmjqGTGm8iY1mRm9qaFxY-gIREXmB_GLu5mA4E/edit#)

Responsible person(s) for this task - Meeting host 

Communicated process during Admin Stand up.
