### ISSUE TITLE
Stephen Lee on Clinical Scenario Listserv Today Please! 26May

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#19]
Stephen Lee wants to know if he is on the Clinical Scenario Listserv. I don’t have permissions to see it.
Will you double check that Stephen Lee has been added to the Clinical Scenario group and please confirm with him (cc:me).

**Comment by dietzr** [comment]
@andrewjneumann has taken care of this request.
