### ISSUE TITLE
Set up weekly bulletin

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/operations#2]
We need a mechanism to report status of hte workstreams and the hubs in each week's bulletin, and a way to archive them on the covid.cd2h.org site. 

Their distribution should be coordinated with CLIC

**Comment by monicacecilia** [comment]
@amvolz

**Comment by amvolz** [comment]
Per Mariam, bulletin content should be sent to Ken with cc: Mariam, Usman every Monday am for approval by NCATS. Approved content will be turned around in 48 hours/Weds. Bulletin can be disseminated after that. A Constant Contact template has been set up, but can only be sent to the listservs CD2H owns (N3C All Hands, CD2H All Hands). CLIC owns the iEC and CTSA mailing lists so bulletin will have to be sent from them to reach those groups. Andrea requested options for this process from CLIC, but have not gotten a response yet.

**Comment by amvolz** [comment]
Per NCATS meeting 5/7/2020: N3C Weekly Bulletin now will be sent to Emily Carlson emily.carlson@nih.gov every Monday 9 am PT, with cc: Usman and Mariam. Emily will review and forward to appropriate people at NCATS for their review. (Eventually may be handed to another person as the point of contact.) 

Approved content is returned on Wednesdays and placed in Constant Contact template (for now). Mailed to CD2H All Hands & N3C All Hands Listservs. (Mailing lists must be exported and updated each week.) Melissa then forwards Constant Contact bulletin to CLIC for dissemination to their listservs.
