### ISSUE TITLE
N3C Collaborative Analytics Portals and Dashboards Weekly Meeting- New (later) time needed

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#20]
N3C Collaborative Analytics Portals and Dashboards Weekly Meeting needs a later time. It is currently at 7am which is a little early for some of the westcoast people. Will you find another time to start the week of June 2nd or June 3rd. 

Rafael will you provide Racquel with the key attendees (Leads/PMs) so she can work around their schedules

Thank you,
Anita

**Comment by dietzr** [comment]
Per Rafael, the most essential attendees are Rafael, Usman, Dave, and Warren. I have sent a [Doodle](https://doodle.com/poll/bnrif3h27eg6w6mm) to those four.

**Comment by dietzr** [comment]
This meeting has been rescheduled to Wednesdays at 11am PT/1pm CT/2pm ET. The invite has been updated.
