### ISSUE TITLE
Leads Call Modify Friday's 29May schedule from 12pmET to 2pm ET 

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#22]
We are going to move the Friday Lead's meeting from Friday at 12pm ET to 2pm ET on the 29th.

Let's see if this works for all future Leads calls too.

**Comment by cgcook** [comment]
@waldenan @mellybelly Double checking on this request, as I saw a slack message (N3C-admin) from Melissa around the same time as this ticket re: moving the SC call.

Can either of you confirm meeting times for this Friday:
Leads: 9a PT or 11a PT
SC: 9a PT or 11a PT

Thanks.

**Comment by mellybelly** [comment]
I think we are keeping the leads call the same, and shooting to move the SC to a full hour at 11PT. I checked with @waldenan and she seemed to think that would work. Please let me know if you think otherwise, else please make it so.

**Comment by waldenan** [comment]
Connor either is fine with me.  Whichever meeting is easier to move.   If
we keep the SC during the normal time from 9-10am we may have more
attendance from them.
Anita Walden

**Comment by cgcook** [comment]
The SC should have 9-10a PT already blocked on their calendars for Friday.  The N3C leads have 930-10a PT blocked.

To my knowledge we haven't asked either the SC or the N3C leads about the 11-12p PT time on Friday. 

Which meeting are we moving?  And do we need to confirm all/a majority of the SC or leads can attend at 11a PT, or is the idea just to move the invite?  

Thanks!

**Comment by waldenan** [comment]
I would suggest keeping our SC at the normal time 9-10 and move the Leads
to 11am.

Anita Walden

**Comment by waldenan** [comment]
Thank you!
Anita Walden

**Comment by cgcook** [comment]
Confirming SC call will be 9am PT and the N3C Leads will move to 11-12p PT.  Meeting invite will be updated shortly.

@dietzr pls close ticket once you updated the calendar invite.  Thanks!

**Comment by dietzr** [comment]
N3C Leads invite has been moved to 11am PT tomorrow. This is 30 mins per Anita on the N3C Admin daily stand up today. Once we decide on a new weekly time I will update the invite accordingly.
