### ISSUE TITLE
Onboarding Slack Use Issue Please Fix by 28May

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#23]
Chunlei Wu report this earlier today...I don't know if I can attach the email so I copied it. It may be an onboarding process issue.

Connor,  Will you 

- [x] address the issue

- [x] Follow up with Deepack and Chunlei today

Hi Rafael,

           I invited Deepak Unni (deepak.unni3@lbl.gov) from the Translator project to join N3C analytics workstream. Look like he is having some issues to join slack channel:

“Hi Chunlei. I am trying to log into the CD2H Slack to get into the Collaborative Analytics channel from this page: https://covid.cd2h.org/N3C_analytics

10:22

But it looks like I don’t have an invite to that workspace

10:22

I did the onboarding way back in April, but never heard from anyone about that

10:22

Let me know if I am doing something wrong or if I should reach out to a point of contact for all things N3C

10:22

Cheers!”

 

         Not sure if any manual step is required after a person is onboarded, can you please help him to sign up those N3C channels, listsrvs and meeting invites, etc? (Also cc’ing Anita in case this is something handled at N3C level, instead of at our workstream) Thanks!

**Comment by cgcook** [comment]
Confirming I sent Deepak a slack invite; and a follow up email to him, Chunlei and Anita.
