### ISSUE TITLE
Identify email address for privacy notice.

### ISSUE THREAD

**Issue by monicacecilia** [National-COVID-Cohort-Collaborative/operations#29]
I received a question: __Is there a contact email for N3C that could be displayed on the (NCATS/N3C) privacy notice?__ 

@mellybelly:
- Is data2health [at] gmail [dot] com the appropriate one for them to use? This is the address that is offered as 'contact info' in the N3C All Hands Bulletin. It does not include the word 'N3C' in the address. 
- NCATS generated this address: N3C [at] nih [dot] gov - which was created for the G Suite account.  Would this be an appropriate one? It is not clear to me who has admin access to this account.

**Comment by mellybelly** [comment]
there should be emails for NCATS N3C and CD2H N3C each. These are the two correct ones listed above. I don't know if the CD2H one is needed in this context on the NIH site though? It is certainly fine to list it but CD2H doesn't have any legal authority.

**Comment by monicacecilia** [comment]
Thank you @mellybelly! 🎉 
I think we have what we need, @deacyma. 🌺 
Closing. :bowtie:
