### ISSUE TITLE
Coordinate FAQs between N3C and NCATS websites -Complete by June 19

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#30]
We need to make sure the N3C FAQs are reviewed by NCATS and there is coordination between the groups on the process.

- [x] Establish a process for initial posting of FAQs

- [x] Review process of maintaining FAQs (new FAQs and review of existing incase there are changes)

- [x] Work with NCATS on the Coordination of FAQs between websites

- [x] Report progress on daily N3C Stand up and Leads Calls

**Comment by amvolz** [comment]
Edits are in the works. Many have contributed and commented. Ken Gersing is looking at some specific comments now. Plan to have draft ready to send to NCATS on Fri 6/19. 

There is no process in place yet for what happens when new FAQs are added, and how often the website version will be updated. 

So far, there is no real overlap with the NCATS FAQs, but this will have to be monitored as people add new content.

**Comment by amvolz** [comment]
More FAQs have been compiled and edited, though not quite complete. Per Anita, will put on Fri 6/19 Leadership meeting agenda. Not sure if will be ready for NCATS on Fri 6/19. Will need process for closing document to editing when it goes to NCATS for approval.

**Comment by amvolz** [comment]
First version of FAQs was sent to Emily Marti/NCATS Fri June 19 as directed. Approved FAQs will be color coded on the "source of truth" google doc to indicate that they can be put on the website. web team is creating place on website to place FAQs once approved by NCATS. (See Covid website repository Issue #36.) Melissa has requested first round of approved FAQs to be posted on the website before Weds 6/24/2020.

**Comment by amvolz** [comment]
13 FAQs have been approved by NCATS. New item under ABOUT menu has been created for N3C FAQs. More to come and process to be finalized with NCATS Communications Team. Workstream pages are under development, but will incorporate their respective FAQs as well.

**Comment by amvolz** [comment]
13 approved FAQs were moved to RESOURCES menu along with NCATS FAQs so they can be accessed together. (NCATS Communications Team still to approve more on our list which will be added.) Workstream pages are under development, but will incorporate their respective FAQs as well.

**Comment by amvolz** [comment]
All preliminary changes made by NCATS have been accepted. 13 FAQs have been approved and posted to the N3C website. A reminder was sent today to the NCATS Communications team that there are 22 FAQs that still need approval. Would be great to have more posted to either the N3C or NCATS websites before the soft launch so users will have readily available resources. Some FAQs need NCATS regulatory approval. Waiting for confirmation.

**Comment by cgcook** [comment]
FAQs published:

[N3C](https://covid.cd2h.org/FAQs)
[NCATS](https://ncats.nih.gov/n3c/about/program-faq)

closing ticket.
