### ISSUE TITLE
Establish standard intro slide template for all N3C large workstream meetings 

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#33]
**Needs:**

- [x] identify an owner to facilitate the discussion and implementation
- [x] process document that outlines:

- how to keep slides updated
- which workstream meetings will be displayed
- what will be on the slide
- will sub groups use the slide
- [x] Slide template with following details:

- DTAs sent
- DTAs Executed - 36
- IRB protocols approved – 13
- sIRBs Approved - 10
- local IRBs Approved – 3
- Both DTA and IRB complete – 11
- Sites engaged with Data Acquisition Group
- Sites w/ Data Payload in the pipeline - 4
-          OMOP - 1
-          PCORnet - 2
-          ACT - 0
-          TriNetX - 1

**Comment by ychae** [comment]
@cgcook here's what the Collaborative Analytics slide template would look like with the above information:
![CA-slide-template-screenshot](https://user-images.githubusercontent.com/12868382/85049073-17e78800-b149-11ea-8fb5-faeb65795d46.png)

Is there a single place where all these numbers are tracked and can be ported to the slides?

**Comment by cgcook** [comment]
@ychae there is not a single place where this is tracked; which is why the slides have not been harmonized across the workstreams.  

@tricfran - pls link your tracking sheet here.

@LisaOKeefe1 pls link your tracking sheet here.

@waldenan - pls link any other relevant dashboards (we have access to) here.

**Comment by LisaOKeefe1** [comment]
@cgcook 
Here's my doc that shares the process I go through to track sites from DTA/IRB to connecting with us. https://docs.google.com/document/d/1aBIswkpw5m5nVABRvGs11O3qv6Ug1QRlvW1a_y7PhhE/edit

Here is the DTA spreadsheet (NCATS is owner) I check: https://docs.google.com/spreadsheets/d/1erpo_8QChByp-yqk0tfYutKPzjmeoWRvrkDO1QQ_YfE/edit#gid=0

Here is Tricia's spreadsheet with IRB I check (JHU owner): https://docs.google.com/spreadsheets/d/1kh8UVT239XHHiHPCMTUhiVJWz3Mfx-S4gRrcHGNEVJs/edit#gid=1672062498

Here is the site tracker Emily and I use to track sites once they've passed IRB/DTA OR have popped in on our office hours: https://docs.google.com/spreadsheets/d/1_uZUFcutAG1HWFBPjgosNcVFtm-1_bBm3owqJrzJAzU/edit#gid=0

**Comment by ychae** [comment]
Thank you @LisaOKeefe1!

**Comment by jmcmurry** [comment]
@ychae all of the above that Lisa mentioned are integrated [here](https://docs.google.com/spreadsheets/d/1btafAid_yWUbO6gsZzWOSVRtuipuiQRzmsMxLMJzyhw/edit#gid=1450344994); however each of those also has this identical merged view fed to the respective tabs called "feedIn".

**Comment by ychae** [comment]
Updated requirements list from @jmcmurry's [HUB Status Dashboard - N3C, requirements tab](https://docs.google.com/spreadsheets/d/1btafAid_yWUbO6gsZzWOSVRtuipuiQRzmsMxLMJzyhw/edit#gid=1122609290)
* DTAs sent
* DTAs Executed
* IRB protocols approved
* sIRBs Approved
* local IRBs Approved
* Both DTA and IRB complete
* Sites engaged with Data Acquisition Group
* Sites deposited data
* Sites w/ Data Payload in the pipeline
   * OMOP
   * PCORnet
   * ACT
   * TriNetX
* TBD (placeholder as additional requirements come along)

**Comment by jmcmurry** [comment]
As of right now, it is my understanding that Raju is also tracking the data model choice; however, I'm going to consider [Emily's sheet](https://docs.google.com/spreadsheets/d/1_uZUFcutAG1HWFBPjgosNcVFtm-1_bBm3owqJrzJAzU/edit#gid=0) the SoT for this info. 

What is the definition of pipeline in the above requirements? Eg. Does pipeline start with contact with Emily's team? Does it start with IRB approval? DTA + IRB approval? Happy to wire whatever, I just need clarity. cc: @mellybelly

**Comment by mellybelly** [comment]
This information should be able to be populated from the new master hub tracking spreadsheet to a shared slide that can be imported/linked for each workstream.

the pipeline starts has multiple starting places:
1a) DTA is signed with NIH
1b) IRB is signed locally or with JHU
1c) Emily's team is in contact with the hub (Sites engaged with Data Acquisition Group)
All of these need to happen before data can move on to the next step: "Sites deposited data"

**Comment by jmcmurry** [comment]
For the avoidance of doubt then, "in the pipeline" means that all three of those criteria are met (regardless of order), right?

Also, is this table what is most useful for the last part of the slide?

...|All sites with data in pipeline|All sites in pipeline and also currently passing data 
---|----|----
OMOP |
PCORNet|
ACT|
TrinetX|
i2b2|
TBD|
total | 

Please confirm or clarify

**Comment by LisaOKeefe1** [comment]
@jmcmurry It depends on what "in the pipeline' means to the group at large. For my group having then pass through 1-2 leads them to being in the pipeline with us but that doesn't mean they have deposited data yet.  I'd like @empfff to weigh in. If "in th pipeline" means successfully passing data and onto harmonization, there will be other steps that must be complete.

**Comment by empfff** [comment]
My definition of "in the pipeline" is (1) IRB is done, (2) DTA is done, (3) they have SFTP credentials (which means they've engaged with my group OR Raju in some way), and (4) they've successfully passed at least one data payload.

**Comment by jmcmurry** [comment]
Thank you so much, @empfff. I will stick with your definition as it is the most rigorous and we should put this definition anywhere that fine "in the pipeline" numbers are sold ;)

**Comment by mellybelly** [comment]
that sounds good to me, however the DTAs are sometimes before and sometimes after the IRB. i would remove i2b2 from the table since we don't have any sites sending i2b2, and make the TBD "other" or remove for now. its not really needed.

**Comment by cgcook** [comment]
FYI, this ticket is related to the [Dashboard for Hub Tracking ticket](https://github.com/National-COVID-Cohort-Collaborative/operations/issues/16).  Posting here so all are aware of the other ticket.

**Comment by ychae** [comment]
https://docs.google.com/presentation/d/1sLtzxOU_MZ9quVfYYScrJZ8qHFobWHU3-P58sC4tv50/edit#slide=id.p

**Comment by ychae** [comment]
Here are the remaining items that require input -- the links lead to the specific slide which shows either an example or a template (this list is also present in [this slide](https://docs.google.com/presentation/d/1sLtzxOU_MZ9quVfYYScrJZ8qHFobWHU3-P58sC4tv50/edit#slide=id.g8af2ceb09b_0_913) and is easier to navigate):

- Graphics slide:
  - [Graphic in paper](https://docs.google.com/presentation/d/1sLtzxOU_MZ9quVfYYScrJZ8qHFobWHU3-P58sC4tv50/edit#slide=id.g8b68f8e547_1_0) or [circles & squares](https://docs.google.com/presentation/d/1sLtzxOU_MZ9quVfYYScrJZ8qHFobWHU3-P58sC4tv50/edit#slide=id.g8af2ceb09b_0_570) 
  - Header and footer styles ([minimal](https://docs.google.com/presentation/d/1sLtzxOU_MZ9quVfYYScrJZ8qHFobWHU3-P58sC4tv50/edit#slide=id.g8af2ceb09b_0_570) vs [bold](https://docs.google.com/presentation/d/1sLtzxOU_MZ9quVfYYScrJZ8qHFobWHU3-P58sC4tv50/edit#slide=id.g8af2ceb09b_0_102))
  - Highlight or Box the specific workstream 
  - [Subgroups](https://docs.google.com/presentation/d/1sLtzxOU_MZ9quVfYYScrJZ8qHFobWHU3-P58sC4tv50/edit#slide=id.g8af2ceb09b_0_726) and/or [High-level responsibilities](https://docs.google.com/presentation/d/1sLtzxOU_MZ9quVfYYScrJZ8qHFobWHU3-P58sC4tv50/edit#slide=id.g8af2ceb09b_0_857) and/or [leads/participants](https://docs.google.com/presentation/d/1sLtzxOU_MZ9quVfYYScrJZ8qHFobWHU3-P58sC4tv50/edit#slide=id.g8af2ceb09b_0_485) (this would be a separate slide if we went with the graphic in the paper)

- Which subgroups will use the slides? (if any)
- Should meeting times be displayed? If so, which ones?
- [Status Update Template](https://docs.google.com/presentation/d/1sLtzxOU_MZ9quVfYYScrJZ8qHFobWHU3-P58sC4tv50/edit#slide=id.g8b4ff89868_0_1) - 👍🏻 or 👎🏻


The [Key Stats slide](https://docs.google.com/presentation/d/1sLtzxOU_MZ9quVfYYScrJZ8qHFobWHU3-P58sC4tv50/edit#slide=id.g8af2ceb09b_0_1037) is all good to go thanks to @jmcmurry! The table in the slide is linked to the main table and can be refreshed by clicking the "UPDATE" button.

**Comment by waldenan** [comment]
Hi Yooree,

Thank you for the information. I think 3-4 slides are needed.

   1. The DTA/IRB/DUA Status slide
   2. Announcements slide: This may be a little difficult but N3C wide
   information or Workstream announcements. Example: meeting cancelations, DUA
   has been approved by NCATS...
   3. and a slide where people can indicate what has been accomplishments
   and planned activities similar to slide 14 or 15

If you can prepare those slides and show them to the group for feedback
that would be nice.

Thank you,
Anita
Anita Walden

**Comment by amvolz** [comment]
I can begin working on the slide for style specs, i.e. color palette, font, point size.

**Comment by waldenan** [comment]
thank you! We need this for all of our presentations.
Anita Walden

**Comment by amvolz** [comment]
Style guides:
CD2H [color palette](https://drive.google.com/drive/u/0/folders/1-DjCq1-rGXpZ-m7OvTM1N71TzHb71IKF)
[NCATS Communications Guidance](https://covid.cd2h.org/Communications_Guidance)
Follow [NIH policy 1186](https://policymanual.nih.gov/1186) for use of NIH names & logos

**Comment by amvolz** [comment]
IMPORTANT! NEW NCATS GUIDANCE FOR USE OF LOGOS 7/10/2020
WE CANNOT USE THE PALANTIR LOGO

- NCATS will not openly advertise–through logo usage or with promotional language–companies under contractual agreement with NCATS for the N3C, which includes Palantir, MD Clone, MS Azure, Adeptia, ETL, and Datavant. 
- N3C is also advised to not advertise, as these companies are under contract with NCATS. 
- This does not prevent provision of clear communications related to direct inquiries regarding the software and tools that NCATS is using to support the platform.
- Additional guidance for use of NIH names and logos: [NIH policy 1186 ](https://policymanual.nih.gov/1186)

**Comment by cgcook** [comment]
New metrics to include in [slide template](https://docs.google.com/presentation/d/1sLtzxOU_MZ9quVfYYScrJZ8qHFobWHU3-P58sC4tv50/edit#slide=id.g8af2ceb09b_0_1037):

- CTSA Organizations participating in N3C 
- Number of Organizations with participants in N3C 
- N3C Individual Members 

Need to operationalize "CTSA Orgs participating" to pull metric.

@waldenan @jmcmurry

**Comment by cgcook** [comment]
The '[key stats' slide](https://docs.google.com/presentation/d/1sLtzxOU_MZ9quVfYYScrJZ8qHFobWHU3-P58sC4tv50/edit#slide=id.g8af2ceb09b_0_1037) is wired up.

There are several templates in the deck now.  

Closing ticket; pls re-open if needed.
