### ISSUE TITLE
Welcome Letter for New N3C Sites - 24June20

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#34]
Need a Welcome Letter for N3C Sites who are on boarding...primarily the Consortium sites.

- [x] Andrea will you harmonize the Welcome Packet letter and this [email letter](https://docs.google.com/document/d/1S0dxlZ5ukxCAlS8LxjypAvM3H7UDM3kkZ4vXedMS6l0/edit) template.

- [x] Send the draft to Anita and Tricia for review and consist messaging across site communications

- [x] once Tricia and Anita has reviewed it then we will review it with NCATS (Ken/Emily) by 22June20

- [ ] Create a process document (location of the letter, updates rollouts... 24June

**Comment by amvolz** [comment]
Harmonized and updated letter information to create new template. Emailed to Anita & Tricia for review.

**Comment by amvolz** [comment]
https://docs.google.com/document/d/1S0dxlZ5ukxCAlS8LxjypAvM3H7UDM3kkZ4vXedMS6l0/edit

**Comment by waldenan** [comment]
Let's try two versions. A welcome packet version and an email version that is much shorter and similar to what was in the example.  

Will you work on an email version that is similar to the one I provided. This can be used by Ken when communicating to sites.

Example:
Step 1. IRB approval to transfer the limited data set.  John Hopkins University has set up a central IRB. and will serve as the reviewing IRB for institutions to transfer data.  Using JHU cIRB is optional and your institution may choose to use a local IRB instead.  Tricia Francis pfranci4@jhu.edu at JHU leads this effort and will  reach out to you to help guide you. 

Step 2. Data Acquisition – In order to assist sites transfer data, N3C has written a series of scripts we will give to you that will pull the data based on the institution's particular common data model and database.  Emily Pfaff epfaff@email.unc.edu at UNC will reach out to your technical team and work with you to configure the transfer process

Step 3. Data Harmonization - Once your team is ready to transfer, the data N3C data harmonization team will set-up a sFTP site that is specific to your institution.  The data harmonization team will then ingest the LDS and run of series of quality checks that transform different data models into a harmonized OMOP analytics data set. Davera Gabriel <dgabrie4@jhmi.edu> leads the harmonization team and will reach to you when the time is ready.

Step 4.  Collaborative Analytics – Once your institution has signed the NCATS Data Use Agreement (still in draft) your investigators can apply to get access to the N3C enclave.  To get access, investigators, submit a brief Data Use Request (DUR). This will be reviewed by a data access committee (DAC). The DACs job is to protect the data, ensure appropriateness research and determine the data access tier (LDS, De-Identified or Synthetic) that is needed.  Investigators will then be given access to NCATS collaborative analytics platform.  The NCATS collaborative analytics platform is very secure, and is located within the Federal Governments GovCloud AWS instance that Federal Risk and Authorization Management Program (FedRAMP) Moderate. The NCATS collaborative analytics platform is a data enclave meaning no data is allowed to leave the platform.    Access to the analytics platform is free of charge and includes both training and ongoing support. Justin Guinney justin.guinney@sagebase.org. is the team lead for analytics

**Comment by amvolz** [comment]
Here is the shorter (slightly) email version for Ken to use.
https://docs.google.com/document/d/1VGGqCq7ERC0fYW1hGHEgi-EZ_8JXycz2htezKcjRto8/edit

**Comment by amvolz** [comment]
This ticket sparked the need to revise the Welcome Letter in the Partnership Packet, which is now almost the same as this welcome letter. The email created is a slightly shorter version of this letter. Per Issue #38, the revised Partnership letter was sent to NCATS to review.  (Seems like a lot of correspondence saying essentially the same thing; difficult for version control if something gets changed on one of them.) 

Once this is all finalized by NCATS, the Partnership Packet needs to be re-PDFd with the revised documents and swapped out on the website.

**Comment by waldenan** [comment]
Ken just sent me a revised version. We should meet tomorrow or Monday to
compare the two. I will send it to you.
Anita Walden

**Comment by cgcook** [comment]
This ticket appears to be done; closing.
