### ISSUE TITLE
make sure all marker paper authors are on N3c-allhands

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/operations#35]
form is here: https://docs.google.com/spreadsheets/d/1As6C9zGorfqwGWdRvf-YRzdeEduhxNG5K1sYjXMsBtY/edit#gid=1642696804

please reassign if needed

**Comment by cgcook** [comment]
All [listed paper authors](https://docs.google.com/spreadsheets/d/1As6C9zGorfqwGWdRvf-YRzdeEduhxNG5K1sYjXMsBtY/edit#gid=1642696804) are on the N3C-allhands list, except:

- Michael Kurilla
- Joni Rutter
- Lora Lingrey
- Gordon Bernard
- Ebony Boulware
- Christopher Mason
- Anna O'Malley

@mellybelly would you like me to add these individuals directly to the list?

**Comment by cgcook** [comment]
per conversation, all listed paper authors above have been added to the N3C-allhands list.
