### ISSUE TITLE
Tooling Certification Criteria/ Requirements for the Enclave 

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#36]
The Governance Group has requested that the tooling and Palantir teams design a process to certify tooling & software.

*Certified Software can be made available in -Verified to not return identified results or row level data according to the Data Access Tiers.

A verification process is needed to document to include but not limited to:

- Validation of new software/tools
- Validation when changes are made to software

A Validation process document will be needed

- Documentation that a tool was certified with certification date, who...

Once the certification process has been established will you inform the Governance group and present it during one of their meetings.

**Comment by andrewjneumann** [comment]
Inprogress in JIRA
