### ISSUE TITLE
Update Welcome packet text-to correct the Non US Citizens Statement - Due July 1st

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#38]
NCATs realized there was an issue with the text in the welcome packet.

There is a misstatement in our welcome packet.  We are able to allow non-US citizens and citizen scientist access to the N3C portal HOWEVER we are NOT able to accept any data from foreign sites. 

- [x] Will you update the text

- [x] Send the revised version to Emily or her back up for NCATs review (asking her to review the changed information only)

- [ ] version the materials/Create a Change Log and include it in the materials
- [ ] Upload the revised document to the Website (indicate version using date)

**Comment by amvolz** [comment]
@waldenan I am updating the Welcome Letter in the Partnership Packet as well, because it is out of date. However, I do not see where the citizen statement is mentioned. Can you please clarify which document in the packet you are referring to? There are many.

**Comment by amvolz** [comment]
@waldenan Updated slides 2 & 5 in the N3C Governance-20200508 slide deck. (We should update the date in the title when approved by NCATS.) Also updated the Partnership Packet Cover Letter and the Contacts & Workstreams list. Sent all 3 documents to NCATS Communications Team for approval.

**Comment by waldenan** [comment]
Thank you!
Anita Walden

**Comment by amvolz** [comment]
Anita & I revised the Partnership Cover Letter and slides a bit more today. They are in NCATS hands for approving.

**Comment by cgcook** [comment]
This ticket appears to be resolved, [Hub packet cover letter is live](https://covid.cd2h.org/partnership_welcome_packet/chapter_1)

closing ticket; pls re-open if needed.
