### ISSUE TITLE
make draft cross-workstream survey

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/operations#39]
Please make a draft google survey based on the content within these documents. 
Consider length as well as needs from each group. The questions could be binned by group as well.
https://docs.google.com/document/d/1i1_m-QUarxE0JIa9KHkQdGnQFHv3r_Tk4u3ENmbJ7ME/edit

- NLP: rows 1-12 in the linked document?
- tools survey: use all of these
- site survey: Include all qustions in the main document.
- Applicable data model: not sure how to best incorporate these as I understand their goals less, but give it a shot ;-).

**Comment by jmcmurry** [comment]
1) We need a pre-amble explaining the people and circumstances in which this data will be shared.
2) Name and Institution will be asked once

**Comment by jmcmurry** [comment]
Each sub-survey should first be drafted as a spreadsheet. This way we can more effectively consolidate and prioritize.

**Comment by cgcook** [comment]
> Each sub-survey should first be drafted as a spreadsheet. This way we can more effectively consolidate and prioritize.

wireframe started [here](https://docs.google.com/spreadsheets/d/1l7FMuEgdeN4HZ3asSrVr_03-ewGS3DsU26ear3qY5K4/edit#gid=164513418).

form template [here](https://docs.google.com/forms/d/1fVV4fCUK7XOTQLc7yXAcpqUhW0jaVR0VEHpCnvWSFwY/edit).

**Comment by cgcook** [comment]
draft survey [here](https://forms.gle/GufZp6M7HEFp3GSw6).  will be shared with Leads tomorrow (7/7) for vetting; for distribution in bulletin on Wed (7/8).
