### ISSUE TITLE
create onboarding documents

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/operations#4]
We will need a "package" of governance and phenotype/data egress info to send to sites. A draft should be made available by Tuesday. It should include the NCATS Data Transfer Agreement and IRB, as well as phenotype and data pull info, and finally contact info for assistance.

**Comment by mellybelly** [comment]
@empfff also need Chris, Christine

**Comment by waldenan** [comment]
https://docs.google.com/document/d/1kQBkibubdmuy4fy48xaTTX5sGP4Q--zq7Na7UUGNY_I/edit

**Comment by mellybelly** [comment]
looks like another one was already created here: https://docs.google.com/document/d/1dz_L_KNB1dhRNeCOxw0VEa1I3fuHOw7lgv_-fB5xSUY/edit
i have been helping to edit this one

**Comment by cgcook** [comment]
[Partnership Welcome packet ](https://covid.cd2h.org/partnership_welcome_packet) is live, fulfills this request; closing ticket.
