### ISSUE TITLE
N3C end-to-end training plan

### ISSUE THREAD

**Issue by andrewjneumann** [National-COVID-Cohort-Collaborative/operations#50]
Trying to capture this here:

- [x] Identify training needs outside of Palantir
- [x] Identify supplemental training needs based on Palantir existing documentation/training
- [x] Documentation/training for onboarding process
- [x] Documentation/training DUR/DUA process
- [ ] Other needs

**Comment by andrewjneumann** [comment]
@cgcook @waldenan @mellybelly cc FYI

**Comment by andrewjneumann** [comment]
FYI  @National-COVID-Cohort-Collaborative/operations

**Comment by andrewjneumann** [comment]
N3C slack channel: https://cd2h.slack.com/archives/C0177PAJDH8

**Comment by waldenan** [comment]
@oneilsh 
Not sure if you have seen this.

Here is what is in the supplement for the IDeA States. 

Collaborative Analytics: Engaging IDeA-CTR member to maximize their investment 

Training
The N3C Enclave is a secure analytics portal within the NCATS Cloud. IDeA States researchers wishing to study and analyze N3C data will conduct all research within the environment; no data egress will be permitted. Consequently, the enclave will contain all the tools and resources required to extract, filter, transform, compute, and visualize the N3C dataset. The primary compute platform is Palantir Foundry, a Platform as a Service with a full analytical stack supporting database queries, ETL operations, data lineage tracking, code and analytical notebooks using R and Python, visualizations, dashboards, and reporting.

The IDeA-CTR sites participating in N3C will receive training that will enable them to design a robust analytics infrastructure to address the most pressing research questions to their institutions. They will receive training in the following areas 1) collaborative development of solid clinical questions using Machine Learning methods; 2) the N3C Enclave and tools and the enclave 3rd party tools including training on the OHDSI tools; 3) application of those tools to perform analysis; and 4) application of attribution models and dissemination of the research findings. 

Clinical Questions Using Machine Learning Methods
A benefit of the N3C is to inform future rural trials. The Collaborative Analytics Clinical Scenario workstream has task-teams focused on various clinical domains. The IDeA-CTR researchers will develop descriptions and prototype implementations of a variety of collaborative analytics use cases involving clinical scenarios. They will have the opportunity to join the existing task teams or they can create a task team focused on rural health clinical questions utilizing their expertise and specific interests. Training will be provided to instruct them on how to develop analytic questions to be executed on the dataset using machine learning and statistical methods and algorithms. 

The N3C Enclave Tools
The Collaborative Analytics Workstream is providing opportunities for training on the Palantir Foundry system and tools. N3C will train the IDeA States researchers on the available enclave tools and 3rd party tools optimized for clinical analytics on an OMOP repository. The OHDSI community has a rich and mature portfolio of tools supporting OMOP-based research which will be selectively deployed on the NCATS cloud and linked through the Palantir environment using its APIs. Additional tools developed by CD2H, CTSAs, and the IDeA-CTR community will be provided along with training. 
Application of Tools to Perform Analysis
An important aspect of the platform is application to adequately use the tools, methods and integration of the datasets to produce knowledge that is valuable to rural and under-representative populations. This will enable researchers to explore questions using more statistical power. Training will be provided to the informatics and clinical personnel on best practices for utilizing the tools and innovative methods such as machine learning and text analytics best practices. Some sites will provide geo-spatial data that can enhance rural health research using predictive modeling for COVID severity or outbreaks. Instruction on application and use will be provided to the organizations. 

Application of Attribution Models 
The analytics environment automatically tracks provenance in the system as part of the workflow. Users who contribute to the system from creating code to analysis will receive credit for their contributions. The IDeA-CTR informaticist and researchers will receive training on the Contributor Attribution Model (CAM) that will be used to aggregate all contributions. They will also be trained on the various tools that are available to promote and publish their findings, allowing for credit and open science. Finally, such contributions will enable implementation of key findings and subsequent evaluation of outcomes in response to changes in healthcare strategy or clinical care guidelines.

**Comment by andrewjneumann** [comment]
In process in Enclave
