### ISSUE TITLE
Enclave Account Creation Letter Text - Due Aug 31

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#52]
The **Welcome to the N3C Enclave** account creation email is needed for the test Monday. @andrewjneumann is assigned to take the language provided modify it. 

@andrea will you review it and attach it to the Github so we can share it with NCATS to implement it in time for the test Monday morning.

**Comment by andrewjneumann** [comment]
@amvolz has access and made edits

**Comment by amvolz** [comment]
@waldenan I've made some edits with what I know as of yesterday. I do have a couple of questions that need to be addressed. https://docs.google.com/document/d/1kkCDOb-3fmxYXEd0yLSD98evuTSpzQvVvU8UPnYELSE/edit

**Comment by waldenan** [comment]
Andrea even though the message is different will you make the Account Creation and Collaborator email look similar in format and branding. Thanks

**Comment by amvolz** [comment]
The 2 email documents have now been matched for format and branding.
[Welcome Collaborator Email](https://docs.google.com/document/d/1RAZcwYKfQLTdlFEVlj7RlCtDO0oyGzinqIKdwNHJJ7k/edit)
[Enclave Account Creation Email](https://docs.google.com/document/d/1kkCDOb-3fmxYXEd0yLSD98evuTSpzQvVvU8UPnYELSE/edit)

**Comment by waldenan** [comment]
Thank you so very much!!!
