### ISSUE TITLE
Enclave Collaborator Invitation Email - Due 31July

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#53]
Those who are invited as collaborators on a N3C project will be sent a system generated invitation email. Some will have an existing email and some will need an account.
Will you review the draft email make revisions by COB on Friday so we can test it on Monday.

Here is a link to the email draft

[Draft Collaborator Invitation Email](https://docs.google.com/document/d/1RAZcwYKfQLTdlFEVlj7RlCtDO0oyGzinqIKdwNHJJ7k/edit)

**Comment by amvolz** [comment]
Here is the edited Collaborator email.
https://docs.google.com/document/d/1RAZcwYKfQLTdlFEVlj7RlCtDO0oyGzinqIKdwNHJJ7k/edit
