### ISSUE TITLE
[registration] Enclave access need to be a little more prominent on the registration page, maybe positioning: minor

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#54]
Enclave access need to be a little more prominent on the registration page, maybe positioning [minor]

**Comment by eichmann** [comment]
@alexisgraves Let's create a CSS twist that accentuates the two checkboxes, enclave and workstream.

**Comment by eichmann** [comment]
Checkbox labels have been restyled to make them more prominent.
