### ISSUE TITLE
[registration] Accepts any ORCID Id: major

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#55]
Accepts any ORCID Id - major

**Comment by eichmann** [comment]
If the name match fails, how are we to distinguish a valid mapping to someone's name variant from an intentional mismatch?

**Comment by andrewjneumann** [comment]
It might be easier to validate submitted ORCIDs in the background and address dups or mismatches as they happen? Perhaps we just validate the proper format of entered ORCID.

**Comment by eichmann** [comment]
I think all we can do at submission time is validate the syntax. If a user creates an id on the fly, we've no guarantee that we can see it in search results. Names are not necessarily going to match due to name changes, etc.

**Comment by eichmann** [comment]
The form now accepts only valid ORCiD ID patterns - 0000-0000-0000-0000
