### ISSUE TITLE
[collaborator] Collaborator was allowed to access enclave without registration: Catastrophic

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#64]
When invited to a project, the invite link sent brings invitee directly into enclave w/o requiring registration process.

**Comment by eichmann** [comment]
The check for this is necessarily at either UNA or Foundry. I suspect that the tester got as far as they did because their account had been manually whitelisted in UNA for purposes of the test session.

**Comment by cgcook** [comment]
@eichmann, @nqureshi, @keatsk do we have any whitelisted testers/initial users who have not completed the new registration process?

**Comment by eichmann** [comment]
Yes.
