### ISSUE TITLE
[DUR] Not sure of what to do once you gain access to Enclave: Catastrophic

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#67]
Workflow/next steps "bread crumbs", not immediately clear when entering enclave--> perhaps home page?

**Comment by ychae** [comment]
@andrewjneumann @cgcook would you be able to provide a bit more clarity on what this ticket is asking? I'm trying to work out what behavior we want to nudge the users to -- am I correct in assuming that we want the users to go straight to the DUR if it's the first time they land on the Data Enclave homepage?

**Comment by oneilsh** [comment]
I think we can close this one, see screenshot of "step 1, step 2" in the homepage copy gdoc

**Comment by cgcook** [comment]
@oneilsh great; pls you add the link to the gdoc for reference, and then close the issue. Thanks!

**Comment by ychae** [comment]
Here's the link to the [Google Doc](https://docs.google.com/document/d/12fHOaq19mruBetynVpI6_GqgUC1Omgz4xQb8iZsO2WI/edit?ts=5f219edf#heading=h.a88l0sgfqssw) for reference.
