### ISSUE TITLE
Cancel one meeting instance

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/operations#7]
Hello,

Can someone on the admin team cancel Thursday's instance of the phenotype small group call? (half-hour meeting, 12:30 EST). Only need Thursday's cancelled--the rest of the series can stay as is.

Thanks!
Emily

**Comment by dietzr** [comment]
Hi Emily! I can do that. Would you like all Thursday meetings cancelled or just the 4/30 instance?

**Comment by empfff** [comment]
Just the one instance please, thanks!

**Comment by dietzr** [comment]
Occurence cancelled.
