### ISSUE TITLE
We should consider reframing “Non confidential disclosure text” to “Public abstract” with descriptive text along the lines of “To minimize redundancy and facilitate collaborations, all project descriptions will be publicly accessible together with the named collaborators”

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#70]
[From 8/3 user testing](https://docs.google.com/presentation/d/14ZFzZJClSm_F-JLIsuE6vDPuBn6qxMVBvKwy76OR2bM/edit#slide=id.g8d4af254cd_31_0)

**Comment by deacyma** [comment]
The DUR was updated based on Julies suggestions. Please let me know if this ticket is still valid
