### ISSUE TITLE
“Send email to collaborators” link not connected [DUR] form

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#72]
[From 8/3 walk thru](https://docs.google.com/presentation/d/14ZFzZJClSm_F-JLIsuE6vDPuBn6qxMVBvKwy76OR2bM/edit#slide=id.g8d4af254cd_31_0)

**Comment by cgcook** [comment]
Ideally, the same email should be sent to all collaborators at once, and the text of the abstract should be part of the text.

**Comment by waldenan** [comment]
The system will send the email directly to collaborators. This will be attempted for launch.
