### ISSUE TITLE
Need to draft email for users who won’t have a DUA 

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#77]
[From 8/3 testing](https://docs.google.com/presentation/d/14ZFzZJClSm_F-JLIsuE6vDPuBn6qxMVBvKwy76OR2bM/edit#slide=id.g8d4af254cd_31_4)

**Comment by waldenan** [comment]
There are several messages regarding a non linkage of a user to an organization or DUA. The draft messages are located at this link.[messages](https://docs.google.com/document/d/10lrRF5Ca44_Y5Vh-Jw0Cq8BM0XWiJU31u7zI21Iu6Fg/edit)

**Comment by amvolz** [comment]
Agree with Anita. There are several email messages created on this [N3C Data Enclave Screen Message document.](https://docs.google.com/document/d/10lrRF5Ca44_Y5Vh-Jw0Cq8BM0XWiJU31u7zI21Iu6Fg/edit). Please let me know if more is needed.

**Comment by amvolz** [comment]
@cgcook @andrewjneumann  Is there still a need for this ticket? Did the script above address the problem? If so, please close. Thanks!
