### ISSUE TITLE
Prepopulate info from existing onboarding doc

### ISSUE THREAD

**Issue by jmcmurry** [National-COVID-Cohort-Collaborative/operations#78]
Name / primary email and affiliation will come from UNA

Please prepopulate from existing onboarding form info if it was previously provided:

- Google "G Suite enabled email"
- Slack email
- Github handle
- ORCID iD
- Assistant email
- Role/Expertise
- LinkedIn Profile
- Clinicians: Therapeutic area of focus
- Twitter handle
- Email aliases
- Name

**Comment by jmcmurry** [comment]
I spoke with @pnrobinson today and he said that none of his legacy info is making its way to the registration form. @eichmann is this expected behavior?

**Comment by mellybelly** [comment]
a little more info since i was there- he doesn't have inCommon through Jackson lab so used the NIH.gov login. We had to redo the login info for him and as such, he didn't see the usual "projects" and other homepage features.

**Comment by jmcmurry** [comment]
This is also confirmed by the fact that some who have previously onboarded are registering but with no known name captured. An example of this is for Contaxis.

**Comment by jmcmurry** [comment]
Just noting, this is not a bug, it has just not yet been implemented.
