### ISSUE TITLE
Log out is not clear on Enclave landing page- major

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#81]

**Comment by amin-manna** [comment]
@cgcook you can assign this to me

**Comment by cgcook** [comment]
thanks @manna-tmp

**Comment by oneilsh** [comment]
Maybe a "Logout" link to the right of "Terms & Conditions" in the top menu?

**Comment by oneilsh** [comment]
Logout link added in main menu, pushed to prod :)
