### ISSUE TITLE
Clarify wording on DUR Project Plan - change to "rationale" - major

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#84]
Julie will provide updated text.

**Comment by jmcmurry** [comment]
As my part of this is complete, I will un-assign myself :)

![image](https://user-images.githubusercontent.com/3658863/89677572-896ac980-d8a2-11ea-8deb-9844ac28291b.png)

**Comment by deacyma** [comment]
![#84](https://user-images.githubusercontent.com/22172108/90827646-92c84d00-e30a-11ea-9f0c-d8cce8a6fcff.JPG)
