### ISSUE TITLE
Set up the new 'Synthetic Clinical Data' Workstream

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#9]
**The tasks listed below need to be completed by Thursday, 14-May-2020**:

- Name: Synthetic Clinical Data
- @andrewjneumann is the Lead Project Manager
- Here are the slides [N3C_SynthClinData_Workstream_v2[2].pptx](https://github.com/National-COVID-Cohort-Collaborative/operations/files/4612199/N3C_SynthClinData_Workstream_v2.2.pptx)
- [x] Set up a Google Listserv/group (on or before 13-May-2020)
- [x] Update onboarding form so others can join the new workstream
  - question: should we use the Sub group process?
- [x] Move the current subfolder on the Google Drive. Create an official Workstream Folder-There is a folder created under Harmonization -(on or before 13-May-2020)
- [x] Add information about the new workstream to N3C Website @alexisgraves 
- [x] Add information about the new workstream to the N3C Bulletin (for the week ending on 15-May-2020) @amvolz 
- [x] Add details about this meeting to the [N3C Admin dashboard](https://docs.google.com/spreadsheets/d/1BimUSQsy4jlGZlD2DavDlIcZbHL-p4dkbQxhnTnywLc/edit#gid=0) -(on or before 15-May-2020)
- [x] Send announcement to N3C-All-Hands, with details about time and date of the workstream meeting @andrewjneumann 
- [x] Set up a meeting with @dietzr and Philip's group (on or before 13-May-2020)
- [x] Create sub groups - (week of May 18-22) - @andrewjneumann with Philip's advice

**Comment by andrewjneumann** [comment]
Breaking out tasks, as to do's in Synthetic Clinical Data project for granular tracking, will close this issues once all are complete.

**Comment by amvolz** [comment]
My task is done. Unable to check the box above.

**Comment by dietzr** [comment]
First three meetings have been scheduled. We are working on confirming the weekly time.
