### ISSUE TITLE
Title and public abstract of project should be in the email collaborator template- major

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#90]

**Comment by amvolz** [comment]
@cgcook Can you please provide link so I can access this?

**Comment by amvolz** [comment]
Information has been added. https://docs.google.com/document/d/1RAZcwYKfQLTdlFEVlj7RlCtDO0oyGzinqIKdwNHJJ7k/edit

**Comment by cgcook** [comment]
@amvolz sry for delay, I think you have [this doc](https://docs.google.com/document/d/1RAZcwYKfQLTdlFEVlj7RlCtDO0oyGzinqIKdwNHJJ7k/edit) now.

**Comment by amvolz** [comment]
@cgcook Yep; I have done the work and included the link above.
