### ISSUE TITLE
Upon Registration, need a mechanism for notifying people when their DUA is not executed -major

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#91]
revisions needed to draft.

**Comment by amvolz** [comment]
@cgcook I believe this was created on [this document under Variation 2](https://docs.google.com/document/d/10lrRF5Ca44_Y5Vh-Jw0Cq8BM0XWiJU31u7zI21Iu6Fg/edit). Let me know if more is needed.

**Comment by eichmann** [comment]
Done.
