### ISSUE TITLE
Refine registration result email text

### ISSUE THREAD

**Issue by eichmann** [National-COVID-Cohort-Collaborative/operations#93]
https://docs.google.com/document/d/10lrRF5Ca44_Y5Vh-Jw0Cq8BM0XWiJU31u7zI21Iu6Fg/edit

**Comment by amvolz** [comment]
Has been edited here: https://docs.google.com/document/d/10lrRF5Ca44_Y5Vh-Jw0Cq8BM0XWiJU31u7zI21Iu6Fg/edit
Please let me know if something more is needed.

**Comment by cgcook** [comment]
status check: is this still an open issue?  @eichmann @amvolz

**Comment by amvolz** [comment]
I believe it is done. @eichmann agree?

**Comment by eichmann** [comment]
Done.
