### ISSUE TITLE
On N3C Website - Returning User Link needs to be updated on Website to take people to the right Unite link - Catastrophic

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#94]

**Comment by amvolz** [comment]
Per Anita, this is the current [UNITE link](https://auth.ncats.nih.gov/_api/v2/auth/login?redirect_uri=https%3A%2F%2Fauth.ncats.nih.gov%2F_api%2Fv2%2Fauth%2Fpalantir%2Fpalantir_unite%2Fsaml&client=palantir_unite&tenant=palantir&protocol=saml):

**Comment by alexisgraves** [comment]
The link on the returning user button has been changed to the one provided by @amvolz above.
